<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-06T00:30:14Z" name="Default suite" finished-at="2021-05-06T00:30:55Z" duration-ms="41397">
    <groups>
    </groups>
    <test started-at="2021-05-06T00:30:14Z" name="Default test" finished-at="2021-05-06T00:30:55Z" duration-ms="41397">
      <class name="testcasesNG.VerifyLoginFunctionality">
        <test-method is-config="true" signature="Setup()[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:13Z" name="Setup" finished-at="2021-05-05T17:30:14Z" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method is-config="true" signature="CreateReport(java.lang.reflect.Method)[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:14Z" name="CreateReport" finished-at="2021-05-05T17:30:14Z" duration-ms="8" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcasesNG.VerifyLoginFunctionality.VerifyLoginErrorMsg01() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateReport -->
        <test-method signature="VerifyLoginErrorMsg01()[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:14Z" name="VerifyLoginErrorMsg01" finished-at="2021-05-05T17:30:28Z" duration-ms="14736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginErrorMsg01 -->
        <test-method is-config="true" signature="CloseReport()[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:28Z" name="CloseReport" finished-at="2021-05-05T17:30:33Z" duration-ms="4203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseReport -->
        <test-method is-config="true" signature="CreateReport(java.lang.reflect.Method)[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:33Z" name="CreateReport" finished-at="2021-05-05T17:30:33Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcasesNG.VerifyLoginFunctionality.VerifyLoginErrorMsg02(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateReport -->
        <test-method signature="VerifyLoginErrorMsg02(java.lang.reflect.Method)[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:33Z" name="VerifyLoginErrorMsg02" finished-at="2021-05-05T17:30:51Z" duration-ms="18141" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcasesNG.VerifyLoginFunctionality.VerifyLoginErrorMsg02(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [https://1992xyz-dev-ed.my.salesforce.com/home/home.jsp?source=lex] but found [https://1992xyz-dev-ed.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [https://1992xyz-dev-ed.my.salesforce.com/home/home.jsp?source=lex] but found [https://1992xyz-dev-ed.my.salesforce.com/setup/forcecomHomepage.apexp?setupid=ForceCom]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testcasesNG.VerifyLoginFunctionality.VerifyLoginErrorMsg02(VerifyLoginFunctionality.java:127)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLoginErrorMsg02 -->
        <test-method is-config="true" signature="CloseReport()[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:51Z" name="CloseReport" finished-at="2021-05-05T17:30:55Z" duration-ms="4266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseReport -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcasesNG.VerifyLoginFunctionality@26e356f0]" started-at="2021-05-05T17:30:55Z" name="tearDown" finished-at="2021-05-05T17:30:56Z" duration-ms="394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcasesNG.VerifyLoginFunctionality -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
